import { Shield } from 'lucide-react'

interface Props {
  /** Override the default disclaimer text (e.g. per-firm branding) */
  customText?: string
  /** Compact single-line version for PDF headers/footers */
  compact?: boolean
}

const DEFAULT_DISCLAIMER =
  'This report is generated by Vantage and is intended solely for the use of the ' +
  'named recipient. All stress test outputs are hypothetical, based on historical scenarios ' +
  'and mathematical models, and do not constitute investment advice, a guarantee of future ' +
  'performance, or a recommendation to buy or sell any security. Past performance is not ' +
  'indicative of future results. This material is provided for informational purposes only ' +
  'and should be reviewed by a qualified financial professional before any action is taken. ' +
  'Vantage is not a registered investment adviser. © ' + new Date().getFullYear() + ' Vantage.'

export default function ComplianceFooter({ customText, compact = false }: Props) {
  const text = customText ?? DEFAULT_DISCLAIMER

  if (compact) {
    return (
      <div className='flex items-center gap-1.5 text-[10px] text-gray-600 leading-relaxed'>
        <Shield size={9} className='shrink-0 text-gray-700' />
        <span>
          For informational purposes only. Not investment advice.
          AI-generated — verify before client delivery.
        </span>
      </div>
    )
  }

  return (
    <footer className='border-t border-white/6 mt-8'>
      <div className='max-w-7xl mx-auto px-4 md:px-6 py-5'>
        <div className='flex items-start gap-2.5'>
          <Shield size={13} className='text-gray-600 shrink-0 mt-0.5' />
          <p className='text-[11px] text-gray-600 leading-relaxed'>
            {text}
          </p>
        </div>
        <p className='text-[10px] text-gray-700 mt-2 ml-[21px]'>
          AI-assisted outputs — verify before client delivery.
        </p>
      </div>
    </footer>
  )
}
